name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      QLTY_COVERAGE_TOKEN:
        required: true

jobs:
  test:
    uses: ./.github/workflows/build.yml
  sonarcloud:
    needs: test
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  qltysh:
    needs: test
    uses: ./.github/workflows/quality-qltysh.yml
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
